#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'postgresql',
  :git => 'git://github.com/scottmuc/chef-postgresql.git'

cookbook 'phppgadmin',
  :git => 'https://github.com/chef-developers/chef-phppgadmin.git'

cookbook 'mongodb'
# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
